In [34]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

In [35]:
enc = OneHotEncoder()

In [36]:
majors = [['Chemistry'],['Physics'],['Engineering']]

In [37]:
enc.fit(majors)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [38]:
X = enc.transform(majors).toarray()

In [39]:
enc.categories_

[array(['Chemistry', 'Engineering', 'Physics'], dtype=object)]

In [40]:
new_majors = [['Media Studies'],['Physics']]
enc.fit(new_majors)
enc.transform(new_majors).toarray()

array([[1., 0.],
       [0., 1.]])

In [41]:
major_df = pd.DataFrame(X, columns = enc.categories_, dtype=np.int)
major_df

ValueError: Shape of passed values is (3, 3), indices imply (3, 2)

In [42]:
#We can alos use get_dummies function in directly for OneHotEncoder 

In [45]:
df = pd.read_csv('HousingData.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       486 non-null float64
ZN         486 non-null float64
INDUS      486 non-null float64
CHAS       486 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        486 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      486 non-null float64
MEDV       506 non-null float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [48]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [49]:
label_enc = LabelEncoder()

In [53]:
# Using label encoding for transforming Numericals values here
label_enc.fit([50,50,70,80])

LabelEncoder()

In [54]:
label_enc.classes_

array([50, 70, 80])

In [55]:
label_enc.transform([50,50,70,80])

array([0, 0, 1, 2], dtype=int64)

In [56]:
label_enc.inverse_transform([0, 0, 1, 2])

array([50, 50, 70, 80])

In [60]:
label_enc.inverse_transform([0, 0, 1, 2, 2, 1, ])

array([50, 50, 70, 80, 80, 70])

In [62]:
colours = ['Red','Blue','Green']
str_enc = LabelEncoder()
str_enc.fit(colours)
str_enc.classes_

array(['Blue', 'Green', 'Red'], dtype='<U5')

In [63]:
str_enc.transform(['Red','Blue','Green'])

array([2, 0, 1], dtype=int64)

In [64]:
# Alphabetical order is used while transforming categorical values to Numeric

In [65]:
# Similar to OneHotEncoder(X variable) but only thing is LabelBinarizer works on target Label only
from sklearn.preprocessing import LabelBinarizer
num_binarizer = LabelBinarizer()

In [66]:
num_binarizer = LabelBinarizer()

In [67]:
num_binarizer.fit([10, 20, 30]) # Numeric values

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [68]:
num_binarizer.transform([10, 20, 30])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [69]:
num_binarizer.classes_

array([10, 20, 30])

In [70]:
num_binarizer.fit([1, 0, 0, 1]) # binary values

LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [71]:
num_binarizer.transform([1, 0, 0, 1])

array([[1],
       [0],
       [0],
       [1]])

In [72]:
num_binarizer.fit(['yes', 'no', 'no', 'yes'])
num_binarizer.transform(['yes', 'no', 'no', 'yes'])

array([[1],
       [0],
       [0],
       [1]])

In [78]:
num_binarizer.fit(['red','blue','green'])
num_binarizer.transform(['red','blue','green'])

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [80]:
# Using multi label binarizer to represent multiple categories,
# In Multi Label Binarizer every category is represented by its prescene or abscene

In [81]:
from sklearn.preprocessing import MultiLabelBinarizer
mul_label_binarizer = MultiLabelBinarizer()
mul_label_binarizer.fit([])

MultiLabelBinarizer(classes=None, sparse_output=False)

In [90]:
courses = [('Math','Eng'),('Math','Science'),('Geography','Math','Science')]
mul_label_binarizer.fit(courses)
mul_label_binarizer.transform(courses)

array([[1, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 1, 1]])

In [91]:
mul_label_binarizer.classes_

array(['Eng', 'Geography', 'Math', 'Science'], dtype=object)